/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdministrationRouteImport } from './routes/_app/administration'
import { Route as AppCommandesRouteImport } from './routes/_app/commandes'
import { Route as AppCompteRouteImport } from './routes/_app/compte'
import { Route as AppInventaireRouteImport } from './routes/_app/inventaire'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppPersonnagesRouteImport } from './routes/_app/personnages'
import { Route as AppRecettesRouteImport } from './routes/_app/recettes'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationRoute = AppAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandesRoute = AppCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AppRoute,
} as any)
const AppCompteRoute = AppCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AppRoute,
} as any)
const AppInventaireRoute = AppInventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonnagesRoute = AppPersonnagesRouteImport.update({
  id: '/personnages',
  path: '/personnages',
  getParentRoute: () => AppRoute,
} as any)
const AppRecettesRoute = AppRecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connexion': typeof ConnexionRoute
  '/administration': typeof AppAdministrationRoute
  '/commandes': typeof AppCommandesRoute
  '/compte': typeof AppCompteRoute
  '/inventaire': typeof AppInventaireRoute
  '/journal': typeof AppJournalRoute
  '/personnages': typeof AppPersonnagesRoute
  '/recettes': typeof AppRecettesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/administration': typeof AppAdministrationRoute
  '/commandes': typeof AppCommandesRoute
  '/compte': typeof AppCompteRoute
  '/inventaire': typeof AppInventaireRoute
  '/journal': typeof AppJournalRoute
  '/personnages': typeof AppPersonnagesRoute
  '/recettes': typeof AppRecettesRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/_app/administration': typeof AppAdministrationRoute
  '/_app/commandes': typeof AppCommandesRoute
  '/_app/compte': typeof AppCompteRoute
  '/_app/inventaire': typeof AppInventaireRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/personnages': typeof AppPersonnagesRoute
  '/_app/recettes': typeof AppRecettesRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/administration'
    | '/commandes'
    | '/compte'
    | '/inventaire'
    | '/journal'
    | '/personnages'
    | '/recettes'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connexion'
    | '/administration'
    | '/commandes'
    | '/compte'
    | '/inventaire'
    | '/journal'
    | '/personnages'
    | '/recettes'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/connexion'
    | '/_app/administration'
    | '/_app/commandes'
    | '/_app/compte'
    | '/_app/inventaire'
    | '/_app/journal'
    | '/_app/personnages'
    | '/_app/recettes'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration': {
      id: '/_app/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AppAdministrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commandes': {
      id: '/_app/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof AppCommandesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compte': {
      id: '/_app/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AppCompteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventaire': {
      id: '/_app/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof AppInventaireRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personnages': {
      id: '/_app/personnages'
      path: '/personnages'
      fullPath: '/personnages'
      preLoaderRoute: typeof AppPersonnagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recettes': {
      id: '/_app/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof AppRecettesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdministrationRoute: typeof AppAdministrationRoute
  AppCommandesRoute: typeof AppCommandesRoute
  AppCompteRoute: typeof AppCompteRoute
  AppInventaireRoute: typeof AppInventaireRoute
  AppJournalRoute: typeof AppJournalRoute
  AppPersonnagesRoute: typeof AppPersonnagesRoute
  AppRecettesRoute: typeof AppRecettesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministrationRoute: AppAdministrationRoute,
  AppCommandesRoute: AppCommandesRoute,
  AppCompteRoute: AppCompteRoute,
  AppInventaireRoute: AppInventaireRoute,
  AppJournalRoute: AppJournalRoute,
  AppPersonnagesRoute: AppPersonnagesRoute,
  AppRecettesRoute: AppRecettesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
